steps:
        - id: go_version
          name: golang
          args: ["go", "version"]

        - id: pwd
          name: golang
          entrypoint: /bin/bash
          args:
                  - -c
                  - |
                          pwd

        - id: ls
          name: golang
          entrypoint: /bin/bash
          args:
                  - -c
                  - |
                          ls -al

        - id: go_build_cli
          name: golang
          dir: "../kne_cli"
          args: ["go", "build", "main.go"]

        - id: go_test_all
          name: golang
          dir: ".."
          args: ["go", "test", "-v", "./..."]

        - id: packer_build
          name: "gcr.io/gep-kne/packer"
          args: ["debian.pkr.hcl"]
