steps:
        - id: go_version
          name: golang
          args: ["go", "version"]

        - id: go_test_all
          name: golang
          dir: ".."
          args: ["go", "test", "-v", "./..."]

        - id: packer_build
          name: "gcr.io/gep-kne/packer"
          args: ["debian.pkr.hcl"]
